package gemi.fl.evaluator;

public enum AbnormalType {

    DIVISION_BY_ZERO,
    UNDEFINED_BUILTIN,
    UNDEFINED_NAME,
    NON_APPLICABLE_ERROR,
    TYPE_ERROR,
    ARGUMENT_TYPE_ERROR,
    INDEX_ERROR,
    ARGUMENT_COUNT_ERROR,
    PATTERN_ERROR,
    UNCOMPARABLE,
    SIGNAL,
    IO_ERROR,
    ENVIRONMENT_ERROR,
    OTHER
}
